### ISSUE TITLE
Feature request: DMR short messages

### ISSUE THREAD

**Issue by xcvista** [rogerclarkmelbourne/OpenGD77#921] opened 2021-03-09 02:34 UTC
This is a feature requested by a few Chinese users here, since the Brandmeister China 4601 server also have a few SMS-driven services on it, and people found it fun to use it.

Is it possible to re-introduce the DMR short message functionality into the firmware? It is one of the features that existed in the manufacturer firmware.

**Comment by rogerclarkmelbourne** [comment] 2021-03-09 03:04
This is a duplicate of https://github.com/rogerclarkmelbourne/OpenGD77/issues/9

**Closed by rogerclarkmelbourne** 2021-03-09 03:04 UTC
