### ISSUE TITLE
Licensing issues...

### ISSUE THREAD

**Issue by dl9sec** [rogerclarkmelbourne/OpenGD77#652] opened 2020-06-23 18:56 UTC
Hi,

a really cool project, thank you for your efforts.

From my point of view, there are some licensing issues in the project:

- If you put the project under GPL-2.0, you can not restrict it for non-commercial use according to "2.  Basic Permissions". Exceptions are only allowed if they are permissive. You can make your own license based on the GPL taking care of some points. See the GPL FAQ https://www.gnu.org/licenses/gpl-faq.html#ModifyGPL.
(Edit: "non-commercial" could have another legal meaning than you imply to it. E.g. there is a german legal case, where "non-commercial" includes also "non-profit"-organisations. Maybe a CC BY-NC-SA https://creativecommons.org/licenses/ would be a better choice).

- The license file you provide with the firmware binary seems to be incomplete. You should provide all copyrights and all license texts of all source codes in you license file (I saw some copyrighted code under other licenses).

- There is some Apache-2.0 licensed code used in the project. Apache-2.0 is not compatible with GPL-2.0. Be aware of license compatibilities.

- If you provide reverse engineered or extracted binary code within your binaries you are potentially infringing the copyrights of the radio firmware creator. Linking to GPL licensed code seems to be an infringement of that license.

I would suggest to take care about those issues to avoid legal disputes...

Regards, Thorsten

**Comment by rogerclarkmelbourne** [comment] 2020-06-25 22:59
Duplicate of already closed issue.

Please read.

https://github.com/rogerclarkmelbourne/OpenGD77/issues/604

This issue will now be locked.  

Please don't create another duplicate, or it will just be deleted.

**Closed by rogerclarkmelbourne** 2020-06-25 22:59 UTC
