### ISSUE TITLE
"DMR Beep: Both" not working

### ISSUE THREAD

**Issue by rjstone** [rogerclarkmelbourne/OpenGD77#606] opened 2020-05-09 20:27 UTC
In build May 4 2020 8:54:11[ ada9153 ] for GD77, the "DMR Beep: Both" setting doesn't sound the start beep, only the ending beep.

**Comment by rogerclarkmelbourne** [comment] 2020-05-10 01:27
Thats an old commit, which has nothing to do with the DMR beeps.

And I can't reproduce this bug on my radios.

**Comment by rogerclarkmelbourne** [comment] 2020-05-11 23:28
Closed because of no response from the OP.

**Comment by rjstone** [comment] 2020-05-11 23:54
I was copying the commit off the firmware info screen. I’ll just try the next release and see if it still happens. Not sure what’s going on.

**Comment by rogerclarkmelbourne** [comment] 2020-05-12 00:18
The latest versions are now handled by the Github release system.

I'll remove the old SGL files from the latest commit, 
(Its not practical to remove them from old commits)

**Comment by rjstone** [comment] 2020-05-12 03:29
I got it from here https://github.com/rogerclarkmelbourne/OpenGD77/releases/tag/R20200503 Maybe the firmware info screen is displaying the wrong commit hash? I should have installed the latest pre-release not the latest release but I got that mixed up it seems.

**Comment by rogerclarkmelbourne** [comment] 2020-05-12 03:45
OK. F1RMB just reported to me that the beep does not happen 100% of the time.

I'll investigate

**Comment by rjstone** [comment] 2020-05-12 03:52
(This is KV0A BTW, sorry) Some more useful information: I read my codeplug from the radio using the CPS, then wrote the code plug back to the radio and now the start beep seems to be happening all the time, or at least every time I've tried it. (I can't key up too fast or BM will ban me. Let me shut off my hotspot and try it.....)

Ok, I hit PTT 30 times in quick succession and 7 of those times I didn't get the start beep. So rewriting the CP helped some but there still seems to be a little nondeterministic issue of some sort.

**Comment by rogerclarkmelbourne** [comment] 2020-05-12 03:58
Yep.

Its probably a timing problem and may only effect simplex DMR (including simplex hotspots)

I'm investigating it now

**Comment by rogerclarkmelbourne** [comment] 2020-05-12 22:57
Should be fixed by 
https://github.com/rogerclarkmelbourne/OpenGD77/commit/13d42bb5e5a9c699cf4ed3a773be2cd6436bd1d2

**Closed by rogerclarkmelbourne** 2020-05-12 22:57 UTC
Labels: can't replicate
